# Name of the workflow
name: Generate Snake Animation

# Controls when the action will run
on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to write to the repository

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Generates the snake animation files
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          # Your GitHub username
          github_user_name: kaveenexe
          # A list of files to generate
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Pushes the generated files to the 'output' branch
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
